# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

# Custom Window Config
bindd = SUPER, Q, Quit, killactive                                                              # Kill active window
bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus --new-window # Windows kinda bind
# browser
bindd = SUPER, B, Browser, exec, zen-browser
bindd = SUPER ALT, B, Browser (private), exec, $browser --private
# Editors
unbind = SUPER, J # was: Toggle window split
bindd = SUPER, J, Intelij, exec, uwsm app -- intellij-idea-ultimate-edition
unbind = SUPER, C # was: Universal copy
bindd = SUPER, C, VSCode, exec, uwsm app -- code
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
# messaging
unbind = SUPER, G # was: Toggle window grouping
bindd = SUPER, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
unbind = SUPER ALT, G # was: Move active window out of group
bindd = SUPER ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# misc
unbind = SUPER, S # was: Toggle scratchpad
bindd = SUPER, S, Music, exec, omarchy-launch-or-focus spotify
bind = CTRL SHIFT, ESCAPE, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
unbind = SUPER, O # was: Pop window out
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
unbind = SUPER, P # was: Pseudo window
bindd = SUPER, P, Passwords, exec, omarchy-launch-or-focus keepassxc "uwsm app -- keepassxc"

#bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
# bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
# bindd = SUPER CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations" bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
 # bindd = SUPER ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
