window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 1000
  multiplier: 3

window.opacity: 0.5
window.startup_mode: fullscreen

font:
  normal:
    #family: Meslo LG S DZ for Powerline
    family: JetBrainsMono Nerd Font
      #family: mononoki Nerd Font
      #family: Source Code Pro
    style: Medium
  size: 8 
draw_bold_text_with_bright_colors: true

schemes:
  afterglow_dark: &afterglow
    primary:
      background: '#2c2c2c'
      foreground: '#d6d6d6'

      dim_foreground:    '#dbdbdb'
      bright_foreground: '#d9d9d9'
      dim_background:    '#202020' # not sure
      bright_background: '#3a3a3a' # not sure

  # Cursor colors
    cursor:
      text:   '#2c2c2c'
      cursor: '#d9d9d9'

  # Normal colors
    normal:
      black:   '#1c1c1c'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#cacaca'

  # Bright colors
    bright:
      black:   '#636363'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#f7f7f7'

  # Dim colors
    dim:
      black:   '#232323'
      red:     '#74423f'
      green:   '#5e6547'
      yellow:  '#8b7653'
      blue:    '#556b79'
      magenta: '#6e4962'
      cyan:    '#5c8482'
      white:   '#828282'
  
  monokai: &monokai
    primary:
      background: '#272822'
      foreground: '#F8F8F2'

    # Normal colors
    normal:
      black:   '#272822'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F8F8F2'

    # Bright colors
    bright:
      black:   '#75715E'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F9F8F5'
  zenburn: &zenburn
    primary:
      background: '#333333'
      foreground: '#ffffff'

      bright_foreground: '#ffffff'
      bright_background: '#555555'

    cursor:
      text:    '#000000'
      cursor:  '#00ff00'

    normal:
      black:   '#4d4d4d'
      red:     '#bb0000'
      green:   '#98f898'
      yellow:  '#f0e68c'
      blue:    '#96853f'
      magenta: '#ffdead'
      cyan:    '#ffa0a0'
      white:   '#f5deb3'

    bright:
      black:   '#555555'
      red:     '#ff5555'
      green:   '#55ff55'
      yellow:  '#ffff55'
      blue:    '#87ceeb'
      magenta: '#ff55ff'
      cyan:    '#ffd700'
      white:   '#ffffff'
  xterm: &xterm
   # Default colors
    primary:
      background: '#000000'
      foreground: '#ffffff'
   # Normal colors
    normal:
      black:   '#000000'
      red:     '#cd0000'
      green:   '#00cd00'
      yellow:  '#cdcd00'
      blue:    '#0000ee'
      magenta: '#cd00cd'
      cyan:    '#00cdcd'
      white:   '#e5e5e5'

   # Bright colors
    bright:
      black:   '#7f7f7f'
      red:     '#ff0000'
      green:   '#00ff00'
      yellow:  '#ffff00'
      blue:    '#5c5cff'
      magenta: '#ff00ff'
      cyan:    '#00ffff'
      white:   '#ffffff'
  tommorownightbright: &tommorownight
  # Default colors
    primary:
      background: '#000000'
      foreground: '#eaeaea'

  # Normal colors
    normal:
      black:   '#000000'
      red:     '#d54e53'
      green:   '#b9ca4a'
      yellow:  '#e6c547'
      blue:    '#7aa6da'
      magenta: '#c397d8'
      cyan:    '#70c0ba'
      white:   '#424242'

  # Bright colors
    bright:
      black:   '#666666'
      red:     '#ff3334'
      green:   '#9ec400'
      yellow:  '#e7c547'
      blue:    '#7aa6da'
      magenta: '#b77ee0'
      cyan:    '#54ced6'
      white:   '#2a2a2a'
        # monokai & afterglow & zenburn & xterm &tommorownight
colors: *zenburn


selection:
  save_to_clipboard: true

live_config_reload: true

shell:
  program: /bin/fish

cursor:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  shape: Box 
    #blinking: false
    #blink-interval: 750
    
keybindings:
  # fonts
  - { key: Delete, mods: Control, action: ResetFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  # instances
  # something to spawn new instance in same dir
  - { key: Q, mods: Control, action: exit }
